# Generated by Django 3.2 on 2022-05-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
