# Generated by Django 3.2 on 2022-05-20 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_track', '0002_alter_track_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='last_play',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
